version: '3'
services:
  tucovid-db:
    image: postgres:11.3-alpine
    container_name: tucovid-db
    env_file: .env.production
    volumes:
    - /home/kubelab/data/tucovid_data:/var/lib/postgresql/data
    networks:
    - internal
    labels:
    - traefik.enable=false
    restart: always

  tucovid-django:
    build: ./tucovid
    command: sh /tucovid/runserver.sh
    container_name: tucovid-django
    env_file: .env.production
    depends_on:
    - tucovid-db
    labels:
    - traefik.backend=tucovid-django
    - traefik.docker.network=proxy
    - traefik.frontend.rule=Host:detect.service.sci.tu.ac.th;PathPrefix:/
    - traefik.port=8000
    networks:
    - internal
    - proxy
    restart: always
    volumes:
    - ./tucovid:/tucovid

networks:
  internal:
    external: false
  proxy:
    external: true
